### ISSUE TITLE
Colour scheme

### ISSUE THREAD

**Issue by Theus93** [haggen/stopwatch#7]
Hi,

I noticed that you implemented a dark theme in your code. I really like the design for notion and would like to know how to embed it with the dark theme.

Thanks

**Comment by Theus93** [comment]
Yes! If you could implement that, it would be amazing. Thanks

**Comment by Theus93** [comment]
Would love to see this update. Please let me know when it's done, if it's not too much trouble.

**Comment by haggen** [comment]
Sorry for the delay I swear it is still coming! 😅 I'll try to get it done next week.

**Comment by haggen** [comment]
@Theus93 It is done! Load up the app and press `L`. Checkout the README.md for more new shortcuts. Also the color scheme is saved per URL and persists if you're using the same browser. Let me know if you need anything else!
